default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: reddit_development
  username: yaska
  password: yaska

test:
  <<: *default
  database: reddit_test
  username: yaska
  password: yaska

production:
  <<: *default
  database: reddit_production
  username: reddit
  password: <%= ENV["REDDIT_DATABASE_PASSWORD"] %>
